name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # to create release
      issues: write # to post issue comments
      pull-requests: write # to create pull request

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_VERSION: 18.18.2
      STORE_PATH: .pnpm-store

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup deps
        uses: ./.github/actions/install-deps

      - name: Set NPM Token
        run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm ci:publish
          version: pnpm ci:version
          title: '[BUMP] Lançar uma release para o octopost!'
          commit: 'chore: bump packages version'
